# Generated by Django 3.2.4 on 2021-06-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeve', models.CharField(max_length=10)),
                ('thick', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '衣服',
                'verbose_name_plural': '衣服',
            },
        ),
    ]
